# Backup și restaurare pentru systemsettings

post_install() {
    if [ -f /usr/bin/systemsettings ]; then
        if [ ! -f /usr/bin/systemsettings.backup ]; then
            cp /usr/bin/systemsettings /usr/bin/systemsettings.backup
        fi
    fi
}

pre_remove() {
    if [ -f /usr/bin/systemsettings.backup ]; then
        mv /usr/bin/systemsettings.backup /usr/bin/systemsettings
    fi
}

post_upgrade() {
#    post_install
}

